"""Pitch Angle Finder API.

A small FastAPI service that takes a company/product description and returns
2-3 realistic PR pitch angles generated by Groq (Llama 3.3 70B), each with a
concrete newsworthiness rationale. See app/prompts.py for the actual prompt
and the reasoning behind it, and the README for a full writeup.
"""

import json
import logging
import os

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from groq import Groq
from pydantic import ValidationError

from app.prompts import SYSTEM_PROMPT, build_user_prompt
from app.schemas import PitchRequest, PitchResponse

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("pitch-angle-finder")

GROQ_MODEL = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

allowed_origins_env = os.getenv("ALLOWED_ORIGINS", "http://localhost:3000")
ALLOWED_ORIGINS = [origin.strip() for origin in allowed_origins_env.split(",") if origin.strip()]

app = FastAPI(
    title="Pitch Angle Finder API",
    description="Suggests realistic PR pitch angles for a company or product using Groq.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_client: Groq | None = None


def get_client() -> Groq:
    global _client
    if _client is None:
        if not GROQ_API_KEY:
            raise HTTPException(
                status_code=500,
                detail=(
                    "GROQ_API_KEY is not configured on the server. "
                    "Set it as an environment variable (see .env.example)."
                ),
            )
        _client = Groq(api_key=GROQ_API_KEY)
    return _client


@app.get("/")
def root():
    return {
        "service": "pitch-angle-finder-api",
        "status": "ok",
        "docs": "/docs",
    }


@app.get("/health")
def health():
    return {"status": "ok", "groq_configured": bool(GROQ_API_KEY)}


@app.post("/api/pitch-angles", response_model=PitchResponse)
def generate_pitch_angles(payload: PitchRequest) -> PitchResponse:
    client = get_client()

    try:
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": build_user_prompt(payload.description)},
            ],
            temperature=0.7,
            max_tokens=1500,
            response_format={"type": "json_object"},
        )
    except Exception as exc:  # groq raises its own APIError subclasses
        logger.exception("Groq API call failed")
        raise HTTPException(status_code=502, detail=f"Groq API request failed: {exc}") from exc

    raw_content = completion.choices[0].message.content

    try:
        parsed = json.loads(raw_content)
    except json.JSONDecodeError as exc:
        logger.error("Groq returned non-JSON content: %s", raw_content)
        raise HTTPException(
            status_code=502, detail="Groq returned a response that wasn't valid JSON."
        ) from exc

    try:
        response = PitchResponse.model_validate(parsed)
    except ValidationError as exc:
        logger.error("Groq JSON didn't match expected schema: %s", parsed)
        raise HTTPException(
            status_code=502,
            detail=f"Groq response didn't match the expected schema: {exc}",
        ) from exc

    if not response.angles:
        raise HTTPException(status_code=502, detail="Groq returned zero pitch angles.")

    return response
