"""Pitch Angle Finder API.

A small FastAPI service that takes a company/product description and returns
2-3 realistic PR pitch angles generated by Groq (model configurable via
GROQ_MODEL, default openai/gpt-oss-120b), each with a concrete newsworthiness
rationale. See app/prompts.py for the actual prompt and the reasoning behind
it, and the README for a full writeup.
"""

import json
import logging
import os

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from groq import Groq
from pydantic import ValidationError

from app.prompts import SYSTEM_PROMPT, build_user_prompt
from app.schemas import PitchRequest, PitchResponse

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("pitch-angle-finder")

GROQ_MODEL = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

allowed_origins_env = os.getenv("ALLOWED_ORIGINS", "http://localhost:3000")
ALLOWED_ORIGINS = [origin.strip() for origin in allowed_origins_env.split(",") if origin.strip()]

app = FastAPI(
    title="Pitch Angle Finder API",
    description="Suggests realistic PR pitch angles for a company or product using Groq.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_client: Groq | None = None


def get_client() -> Groq:
    global _client
    if _client is None:
        if not GROQ_API_KEY:
            raise HTTPException(
                status_code=500,
                detail=(
                    "GROQ_API_KEY is not configured on the server. "
                    "Set it as an environment variable (see .env.example)."
                ),
            )
        _client = Groq(api_key=GROQ_API_KEY)
    return _client


@app.get("/")
def root():
    return {
        "service": "pitch-angle-finder-api",
        "status": "ok",
        "docs": "/docs",
    }


@app.get("/health")
def health():
    return {"status": "ok", "groq_configured": bool(GROQ_API_KEY)}


MAX_ATTEMPTS = 3
MIN_ANGLES = 2


@app.post("/api/pitch-angles", response_model=PitchResponse)
def generate_pitch_angles(payload: PitchRequest) -> PitchResponse:
    """Call Groq and validate the result, retrying a few times if Groq's own
    JSON-mode generation fails or if it ignores the "2 to 3 angles"
    instruction and returns fewer than 2. Both of these are real, observed
    Groq behaviors (not hypothetical) -- see README "Known limitations."
    Only after every attempt fails does this return a 502, so a genuine
    persistent failure is never silently hidden.
    """
    client = get_client()

    last_error: HTTPException = HTTPException(
        status_code=502, detail="Groq did not return a usable response."
    )

    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            completion = client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": build_user_prompt(payload.description)},
                ],
                temperature=0.7,
                max_tokens=2000,
                response_format={"type": "json_object"},
            )
        except Exception as exc:  # groq raises its own APIError subclasses
            logger.warning("Attempt %d/%d: Groq API call failed: %s", attempt, MAX_ATTEMPTS, exc)
            last_error = HTTPException(status_code=502, detail=f"Groq API request failed: {exc}")
            continue

        raw_content = completion.choices[0].message.content

        try:
            parsed = json.loads(raw_content)
        except json.JSONDecodeError:
            logger.warning(
                "Attempt %d/%d: Groq returned non-JSON content: %s", attempt, MAX_ATTEMPTS, raw_content
            )
            last_error = HTTPException(
                status_code=502, detail="Groq returned a response that wasn't valid JSON."
            )
            continue

        try:
            response = PitchResponse.model_validate(parsed)
        except ValidationError as exc:
            logger.warning(
                "Attempt %d/%d: Groq JSON didn't match expected schema: %s", attempt, MAX_ATTEMPTS, parsed
            )
            last_error = HTTPException(
                status_code=502,
                detail=f"Groq response didn't match the expected schema: {exc}",
            )
            continue

        if len(response.angles) < MIN_ANGLES:
            logger.warning(
                "Attempt %d/%d: Groq returned only %d angle(s), retrying",
                attempt,
                MAX_ATTEMPTS,
                len(response.angles),
            )
            last_error = HTTPException(
                status_code=502,
                detail="Groq returned fewer than 2 pitch angles.",
            )
            continue

        return response

    logger.error("All %d attempts failed; returning last error to client.", MAX_ATTEMPTS)
    raise last_error
